AllCops:
  Exclude:
    - 'src/**/*'
    - 'test/dummy/bin/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'
