AllCops:
  Exclude:
    - 'src/**/*'
    - 'test/**/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'
