require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.4
  Exclude:
    - 'src/**/*'
    - 'test/dummy/bin/*'
    - 'vendor/bundle/**/*'

Lint/InterpolationCheck:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - 'test/**/*'

Style/Documentation:
  Enabled: false
