AllCops:
  DisplayCopNames: true
  TargetRailsVersion: 4.0
  TargetRubyVersion: 2.0
  Exclude:
    - 'src/**/*'
    - 'test/dummy/bin/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - Appraisals

Style/HashSyntax:
  Exclude:
    - 'Rakefile'
