AllCops:
  DisplayCopNames: true
  TargetRailsVersion: 4.0
  TargetRubyVersion: 2.0
  Exclude:
    - 'src/**/*'
    - 'test/dummy/bin/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - Appraisals

# TODO: Remove when targeting Ruby 2.3 because it is already enabled.
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
