language: ruby
sudo: false
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
matrix:
  exclude:
    - rvm: 2.4.6
      gemfile: gemfiles/rails_6.0.gemfile
  fast_finish: true
