language: ruby
sudo: false
rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
matrix:
  exclude:
    - rvm: 2.4.7
      gemfile: gemfiles/rails_6.0.gemfile
  fast_finish: true
